import "./globals.css"
import type { Metadata } from "next"
import { Geist, Geist_Mono, Inter } from "next/font/google"
import { cn } from "@/lib/utils"
import { TooltipProvider } from "@/components/ui/tooltip"
import { ThemeProvider } from "@/context/theme-provider"
import { DirectionProvider } from "@/context/direction-provider"
import { FontProvider } from "@/context/font-provider"
import { Suspense } from "react"
import { Toaster } from "@/components/ui/sonner"
import { AuthProvider } from "@/context/auth-provider"

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col">
        <Suspense>
          <Toaster duration={5000} />
          <TooltipProvider>
            <ThemeProvider>
              <FontProvider>
                <DirectionProvider>
                  <AuthProvider>
                    {children}
                  </AuthProvider>
                </DirectionProvider>
              </FontProvider>
            </ThemeProvider>
          </TooltipProvider>
        </Suspense>
      </body>
    </html>
  )
}